[workspace]
resolver = "3"
members = ["controller", "api", "json-patch-macros", "indexer", "notebook_meta"]
default-members = ["controller"]

[workspace.package]
version = "0.1.10-alpha.0"
license = "MIT"
