[project]
name = "workspace"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = ["marimo>=0.19.9"]

[dependency-groups]
dev = ["ruff>=0.14.11", "ty>=0.0.11", "watchdog>=6.0.0"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
