[project]
name = "workspace"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = ["marimo>=0.18.0"]

[dependency-groups]
dev = ["ruff>=0.13.2", "ty>=0.0.1a21", "watchdog>=6.0.0"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
